package stepDefs;

import org.openqa.selenium.WebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.cucumber.java.en.And;
import io.cucumber.java.en.When;
import pages.FormPage;
import utils.DriverFactory;
import utils.OllamaClient;
import utils.TestDataGenerator;

/**
 * Step definitions for interacting with the sample form page used in tests.
 *
 * <p>The steps are intentionally thin: they delegate form interactions to
 * the {@link FormPage} page object and use {@link TestDataGenerator} to
 * provide realistic test inputs. This keeps Cucumber feature files clean
 * and the Selenium logic centralized in page objects.</p>
 *
 * Notes:
 * - Methods use TestDataGenerator for randomized values. If Ollama-backed
 *   generation fails (see {@link utils.OllamaClient}), TestDataGenerator
 *   returns a sentinel value which may cause the page object to receive
 *   unexpected text; tests should handle that scenario if running in
 *   environments without Ollama.
 */
public class FormStepDefs {

	private static final Logger logger = LoggerFactory.getLogger(FormStepDefs.class);
	static {
		// Ensure consistent logging using the project's logback configuration
		System.setProperty("logback.configurationFile", "logback.xml");
	}
	public WebDriver driver;
	FormPage formPage;

	/**
	 * Constructor sets up shared instances used by the step methods. The
	 * DriverFactory is responsible for providing a configured WebDriver
	 * instance managed by the test runner.
	 */
	public FormStepDefs() {
		this.driver = DriverFactory.getDriver();
		formPage = new FormPage(driver);
	}

	/**
	 * Enters a random first name into the form. The value comes from
	 * {@link TestDataGenerator#randomFirstName()}.
	 */
	@When("I enter first name")
	public void i_enter_first_name() {
		formPage.enterFirstName(TestDataGenerator.randomFirstName());
	}

	/**
	 * Enters a random last name into the form. The value comes from
	 * {@link TestDataGenerator#randomLastName()}.
	 */
	@And("I enter last name")
	public void i_enter_last_name() {
		formPage.enterLastName(TestDataGenerator.randomLastName());
	}

	/**
	 * Enters a random email into the form. The value comes from
	 * {@link TestDataGenerator#randomEmail()}.
	 */
	@And("I enter email")
	public void i_enter_email() {
		formPage.enterEmail(TestDataGenerator.randomEmail());
	}

	/**
	 * Selects a random gender option on the form using
	 * {@link TestDataGenerator#randomGender()}.
	 */
	@And("I select gender")
	public void i_select_gender() {
		formPage.selectGender(TestDataGenerator.randomGender());
	}

	/**
	 * Enters a random mobile number supplied by
	 * {@link TestDataGenerator#randomMobileNumber()}.
	 */
	@And("I enter mobile number")
	public void i_enter_mobile_number() {
		formPage.enterMobileNumber(TestDataGenerator.randomMobileNumber());
	}

	/**
	 * Enters a random date of birth generated by
	 * {@link TestDataGenerator#randomDateOfBirth()}.
	 */
	@And("I enter date of birth")
	public void i_enter_date_of_birth() {
		formPage.enterDateOfBirth(TestDataGenerator.randomDateOfBirth());
	}

	/**
	 * Selects subjects for the form. Currently the page object's subject
	 * selection supports a single subject; the comment in the original code
	 * indicates plans to support multiple selections in future.
	 */
	@And("I enter subjects")
	public void i_select_subjects() {
		// Note: TestDataGenerator.randomSubject() returns one subject string.
		// The form page may need updates to select multiple subjects if
		// the tests require that behavior.
		formPage.selectSubjects(TestDataGenerator.randomSubject());// need some work on this method to select multiple
		// subjects
	}

	/**
	 * Selects one or more hobbies as returned by
	 * {@link TestDataGenerator#randomHobby()}. The page object currently
	 * accepts a single hobby value; expand if multiple hobbies are required.
	 */
	@And("I select hobbies")
	public void i_select_hobbies() {
		formPage.selectHobbies(TestDataGenerator.randomHobby()); // need some work on this method to select multiple
		// hobbies
	}

	/**
	 * Uploads the provided test image to the form. The path is passed
	 * directly to the page object's upload helper which resolves the path
	 * relative to the project working directory.
	 *
	 * @param pathToTestImage local path to the test image file to upload
	 */
	@And("I upload picture {string}")
	public void i_upload_picture(String pathToTestImage) {
		formPage.uploadPicture(pathToTestImage);
	}

	/**
	 * Enters a random current address into the form using
	 * {@link TestDataGenerator#randomAddress()}.
	 */
	@And("I enter current address")
	public void i_enter_current_address() {
		formPage.enterCurrentAddress(TestDataGenerator.randomAddress());
	}

	/**
	 * Selects a state and city combination for the form. Both values are
	 * generated randomly by {@link TestDataGenerator}. If the page requires
	 * a matching state/city pair, consider enhancing the generator to return
	 * valid pairs.
	 */
	@And("I select state and city")
	public void i_select_state_and_city() {
		formPage.selectStateAndCity(TestDataGenerator.randomCity(), TestDataGenerator.randomState());
	}

	/**
	 * Submits the registration form using the page object's submit helper.
	 */
	@And("I submit the form")
	public void i_submit_the_form() {
		formPage.submitForm();
	}

}